### ISSUE TITLE
Switch between Pock and regular touchbar at ease

### ISSUE THREAD

**Issue by marnovo** [pigigaldi/Pock#120]
**Is your feature request related to a problem? Please describe.**

Neither Pock nor the default touchbar controls give individually all the functionality I want.

**Describe the solution you'd like**

I want to have a shortcut or a simple way to "activate" or "open" Pock from the regular touchbar controls (like the control strip), and then to "close it" and go back to the normal one.

**Describe alternatives you've considered**

Be able to bring functionality from the regular touchbar to Pock.

**Additional context**

Pock v0.52, macOS Mojave 10.14.5

**Comment by pigigaldi** [comment]
You can use the double `ctrl` key shortcut to switch from current app Touch Bar and Pock! :)

**Comment by Alecyrus** [comment]
@pigigaldi Maybe the double ctrl key shortcut is not convenient for everyone. Is there possible to customize the shortcut ? Specifically, I could assign any touchPad gesture to the double `Ctrl` key in `BetterTouchTool`, because it could not record double `keyboard modifiers`( Normally, it should be `Modifier`+`other keys`).

**Comment by hansenz42** [comment]
Agree. Users should be able to easily change the shortcut. I am using Karabiner to modifier keys on my keyboard, so it is very useful for me to avoid conflicts if I could change double `Ctrl` key shortcut.
