### ISSUE TITLE
"Now playing" widget not displaying the app's logo

### ISSUE THREAD

**Issue by Darktortue** [pigigaldi/Pock#254]
**Describe the bug**
"Now playing" widget not displaying the app's logo anymore

**How to reproduce**
```
1. Launch a browser like Safari, Opera.
2. Launch any sound/video
3. Check the "Now Playing" widget
```

**Expected behavior**
When I listen to music or watch a video on a browser it displays the logo of the browser.

**Screenshots**
<img width="1085" alt="Capture d’écran Touch Bar 2019-10-11 à 10 09 56" src="https://user-images.githubusercontent.com/11302315/66635470-9d588700-ec0f-11e9-95b8-ece39b2bbf6c.png">

**Versions:**
 - macOS version: 10.15
 - Pock version:  0.6.2

**Additional context**
The bug only exists with audio/video from a browser. When I listen to music on the spotify app it works fine.

**Comment by maxisvest** [comment]
same issue, and it not support fore-back song.

**Comment by rorydavidson** [comment]
I had this issue, but followed the instructions here - https://pock.dev/docs/catalina.html - and the relevant app icon returned. See if that works?

**Comment by Darktortue** [comment]
Yeah I already did this before but surprisingly for me pock doesn't show up in the "screen recording" part. Maybe that's the cause of the problem ?

**Comment by wgxdz** [comment]
I followed the instructions and granted all the permissions for Pock. However, I still have the same problem. After playing any media in any browser, the icon in "Now Playing" widget will crash...

**Comment by pigigaldi** [comment]
Supported applications for the NowPlaying widget can be found in this [file](https://github.com/pigigaldi/Pock/blob/2467199e5cc5f4f4b107f784b49b60ce34d47c2b/Pock/Widgets/NowPlaying/NowPlayingItemView.swift#L45).
As you can see in the code, if an application is not known, Pock should fallback to the iTunes/Music app (it depends on which version of macOS is running).
While I was writing this comment, I found out that the check on the macOS version is done on `13` instead of `10.15`.
A new release with this fix is already on the road!

**Comment by antoinerousseau** [comment]
How about simply removing the app icon to gain some space? For me the song title/artist is enough :)

**Comment by pigigaldi** [comment]
Update to the latest version that includes a fix for this issue.
