### ISSUE TITLE
Now Playing Widget Chromecast issue

### ISSUE THREAD

**Issue by guaiamum** [pigigaldi/Pock#313]
**Describe the bug**
Whenever I switch playing to my chromecast, the touchbar widget gets way wider and no text on it, like in the screenshot
 

**How to reproduce**
```
1. Now playing in mode with any layout that displays `Media item information`
2. Open spotify and play a song
3. Click on devices available and switch to chromecast device. I did not encounter the issue playing on other devices...
4. See error
```

**Expected behavior**
Show meaninful info and not occupy full width

**Screenshots**
<img width="1085" alt="bug" src="https://user-images.githubusercontent.com/21321095/70863298-7e8fad00-1f3e-11ea-87e2-9aafc0a1fd9a.png">

**Crashlog**
This log keeps showying up, don't know what it is, but it does seem to appear when disconnected from chromecast.

``` 
Request: playbackQueue<_bigHexNum_ Pock-5663 /M/L/_lotofzeroes_/R[0:1]> for origin-(null)-0/client--0/player-(null)
```

**Versions:**
 - macOS version: 10.15.2
 - Pock version:  0.7

**Comment by pigigaldi** [comment]
Sometimes playing music throughout external devices (like Chromecast) causes `MediaRemote.framework` to not have the correct information about the currently playing item.

You can check this issue by opening the **macOS Notification Center** and adding the default *"Now Playing Widget"* in it. 
You will notice that it will not display any information about the current track.

Since **Pock** uses the same framework for retrieving media information, the issue is present also in **Pock**.

A fix for the `full-width` glitch is coming, but I can't confirm it will always show the correct info while using external devices.

Thanks!

**Comment by guaiamum** [comment]
Noice! Do you think is possible to have a fallback text in case MediaRemote does not retrieve anything? Maybe "Not available" or something of the sorts..
