### ISSUE TITLE
one icon for one window 

### ISSUE THREAD

**Issue by ShangyinGao** [pigigaldi/Pock#74]
Is it possible to support the feature, one icon for one window

I always open multi chrome windows. It's very helpful if I can directly switch between chrome windows on Touchbar

**Comment by cbusby-oportun** [comment]
If I might change your mind...

long-press an icon for a list of windows and allow you to select the specific window title.

**Comment by larsblumberg** [comment]
I was about to create the same feature request: Long touch an app icon in order to show all open windows of that app. Then – without lifting the finger (!) – I move my finger to the wanted window. By lifting the finger the selected window foregrounds.

Of course I could also tap again on the window after having long-touched the app icon.

Both ways should work.

**Comment by larsblumberg** [comment]
I was about to create the same feature request: Long touch an app icon in order to show all open windows of that app. Then – without lifting the finger (!) – I move my finger to the wanted window. By lifting the finger the selected window foregrounds.

Of course I could also tap again on the window after having long-touched the app icon.

Both ways should work.

**Comment by larsblumberg** [comment]
I was about to create the same feature request: Long touch an app icon in order to show all open windows of that app. Then – without lifting the finger (!) – I move my finger to the wanted window. By lifting the finger the selected window foregrounds.

Of course I could also tap again on the window after having long-touched the app icon.

Both ways should work.

**Comment by diego898** [comment]
I was about to open a feature request for long request to show minimized windows. Please advise if we should open a new one (and not hijack this one!)

**Comment by Aquaj** [comment]
Another possibility which might involve less development could be to mirror Dock behaviour and switch from window to window when you click on the app.

Here is an example switching between my 4 Firefox windows using the Mac OS X dock.

![example-dock-switching](https://user-images.githubusercontent.com/2871879/60174474-63ef3d80-9811-11e9-854a-1b6678cb64d4.gif)

**Comment by pigigaldi** [comment]
App Exposé feature is available from version 0.6 🎉
