### ISSUE TITLE
Add support for customizing control center widget buttons

### ISSUE THREAD

**Issue by Einkoro** [pigigaldi/Pock#82]
It would be nice to choose different or additional buttons from the four (brightness and volume) currently available in the control strip widget. Specifically the lock button as I find myself using it the most frequent of any TouchBar controls since there isn’t a good shortcut anymore.

**Comment by pigigaldi** [comment]
Pock 0.5 has a built-in control center that is useful if you have the `Hide Control Strip` checkbox enabled. I'll keep this issue open until I add the `Lock Item` in Control Center widget.
If you preferer you can still use the system Control Strip and configure it from `System Preferences -> Keyboard -> Customise Touch Bar...` settings.

**Comment by edwardgalligan** [comment]
+1 on making this about the Lock button (came here looking for an existing issue just for that).

Don't think any customisation would be as needed if that button alone were added

**Comment by gsprenger** [comment]
Mute button and lock button are the two ones I use the most personally.
It would be great to see them in the Control Center widget as togglable options, especially since activating the system Control Strip has the big downside of causing the close button to appear on the left where the ESC usually is (which reduces available horizontal space and pushes the custom ESC button to the right)
Right now we have to chose between the lesser of two evils (displaced esc button vs. missing command center controls)

**Comment by TrollDoc** [comment]
Have a similar request. I use the keyboard backlight buttons a lot and that's the only thing that is keeping me away from using pock.
I guess you need to give a thought about making the control center widget customizable?

**Comment by pigigaldi** [comment]
187d4e024322077c9cfbed61a538424a52fc00a9
