### ISSUE TITLE
Toggling the "Hide Control Strip" option results in two escape keys

### ISSUE THREAD

**Issue by afollestad** [pigigaldi/Pock#94]
**Describe the bug**
Title is self explanatory.

**To Reproduce**
1. Preferences -> General -> Hide control strip
2. Turn it on and off.
3. The esc key appears twice in the touch bar.

**Expected behavior**
Only one escape key remains.

**Screenshots**
![image](https://user-images.githubusercontent.com/1820165/59980020-d90a0b00-95a4-11e9-9b7e-1303888d61d9.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome
 - Version: 0.5.1

**Comment by pigigaldi** [comment]
I need to clarify a thing:
The "double-esc-button" situation is normal if you have the `Hide Control Strip` option unchecked and you open Pock's preferences.
This condition happens because, since that option is disabled, Pock is showed inside system Touch Bar and is not replacing it (like it would do with that option enabled). 
So, while you're on preference panes, Pock is the frontmost application, and the system Touch Bar thinks it's necessary to add the default "esc" button because it doesn't know that Pock already owns one.
If you switch to any another application, the default "esc" button disappears so that you can see only the Pock's one.

**Comment by lorenzofanchi** [comment]
Could you, just for aesthetic reasons, temporarily remove the Esc button while in these situations?
