### ISSUE TITLE
"X" (close) button visible to the left of ESC

### ISSUE THREAD

**Issue by ssobczak** [pigigaldi/Pock#97]
**Describe the bug**
I'm used to the location of ESC button on the very left, it should stay in the same place. Now I see [X] (close) button first, and ESC comes second.

**To Reproduce**
I think I haven't had that at the beginning, now I see this permanently - even just after I quit & restart Pock

**Expected behavior**
ESC should be the first icon on the very left.

**Screenshots**
<img width="1085" alt="Touch Bar Shot 2019-06-24 at 2 00 24 PM" src="https://user-images.githubusercontent.com/605104/60017254-9cafdb00-9688-11e9-995a-9fc2e39f8cf9.png">

**Desktop (please complete the following information):**
 - OS: OS X 10.14.05

**Comment by pigigaldi** [comment]
This condition is perfectly normal if you have `Hide Control Strip` option disabled. That's because, with that option disabled, Pock is showed inside system Touch Bar and is not replacing it, and since Pock is showed inside the system Touch Bar, the user should have the ability to close it to switch to current frontmost app's Touch Bar.

**Comment by ssobczak** [comment]
Got it, after changing that it works as expected. Thanks! Maybe this would be a good section for some  HOWTO or FAQ, I think it's not obvious for "regular" users like me :)

**Comment by pigigaldi** [comment]
FAQ section is coming 🏄🏻
https://twitter.com/pigigaldi/status/1142862572733063168?s=21
